FORMAT: 1A
HOST: https://us-central1-nangarok-camp-run1.cloudfunctions.net/api/v1/

# Nangorak Project API Docs

This document documented all API that will be used to build nangorak websites.

## Images [/images]
### Get a sized image [GET /images]
+ Request (application/json)
    + Attributes
        + fileName: `alif.png` (string , required)
        
+ Response 200 (application/json)
    + Attributes
        + fileName: `alif.png` (string)
        + sized (array)
            + full: `https://googleimage.com/alif.png` (string)
            + 0: `https://googleimage.com/alif_0.png` (string)
            + 1: `https://googleimage.com/alif_1.png` (string)
            + 2: `https://googleimage.com/alif_2.png` (string)

## Attractions [/attractions]
### Get all attractions [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + venueId: `1536250994397` (string) - nangorak
            + note: `Temukan keindahan alam yang tidak kamu temukan di belahan bumi manapun. Pemandangan yang seperti layaknya sepenggal surga di muka bumi.` (string)
            + attractions (array[Attraction])
        + (object)
            + venueId: `1536250994398` (string, required) - situ bagus
            + note: `Temukan keindahan alam yang tidak kamu temukan di belahan bumi manapun. Pemandangan yang seperti layaknya sepenggal surga di muka bumi.` (string)
            + attractions (array[Attraction])

### Get all attractions of venue [GET /attractions{?venueId}]
+ Parameters
    + venueId: `1536250994397` (string, required) - nangorak
+ Response 200 (application/json)
    + Attributes
        + venueId: `1536250994397` (string) - nangorak
        + note: `Temukan keindahan alam yang tidak kamu temukan di belahan bumi manapun. Pemandangan yang seperti layaknya sepenggal surga di muka bumi.` (string)
        + attractions (array)
            + (Attraction)
            + (Attraction)

## Facilities [/facilities]
### Get all facilites [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + venueId: `1536250994397` (string) - nangorak
            + backgroundImage (array[string])
            + facilities (array[Facility])
        + (object)
            + venueId: `1536250994397` (string) - nangorak
            + backgroundImage: `asd.png` (string)
            + facilities (array[Facility])

### Get all facilities of venue [GET /facilities{?venueId}]
+ Parameters
    + venueId: `1536250994397` (string, required) - nangorak
+ Response 200 (application/json)
    + Attributes
        + venueId: `1536250994397` (string) - nangorak
        + backgroundImage: `asd.png` (string)
        + facilities (array)
            + (Facility)
            + (Facility)

## Venue [/venues]
### Get all venues [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (Venue)
        + (Venue)
        + (Venue)

### Get specific venue [GET /venues{?venueId}]
+ Parameters
    + venueId: `1536250994397` (string, required) - nangorak
+ Response 200 (application/json)
    + Attributes (Venue)

## Feedback [/feedbacks]
### Get all feedbacks [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (Feedback)
        + (Feedback)
        + (Feedback)

### Get all feedbacks of venue [GET /feedbacks{?venueId}]
+ Parameters
    + venueId: `1536250994397` (string, required) - nangorak
+ Response 200 (application/json)
    + Attributes (array)
        + (Feedback)
        + (Feedback)

### Get a feedbacks [GET /feedbacks{?id}/]
+ Parameters
    + id: `1536841607814` (number, required)
+ Response 200 (application/json)
    + Attributes (Feedback)


# Data Structures

## Address (object)
- street: `Jl. Gunung Puyuh – Nangorak Blok Nangorak, Desa Margamekar` (string, required)
- district: `Kec. Sumedang Selatan` (string, required)
- city: `Kab. Sumedang` (string, required)
- province: `Jawa Barat` (string, required)

## Contact (object)
- email: `nangorakcamp@gmail.com` (string, required)
- phone: `+62 821 1915 8765` (string, required)n
- facebook: `fb.com/m.alif.akbar` (string)
- instagram: `instagram.com/muh.alifgiant` (string)
- twitter: `twitter.com/alifgiant` (string)
- googlePlus: `plus.google.com/alifgiant` (string)

## Venue (object)
- name: `Nangorak camping site` (string, required)
- logo (array[string]) - only 1 image
    - asd.png
- heroImages (array[string]) - up to 4 image
    - asd.png
    - asd.png
- note: `Temukan keindahan alam yang tidak kamu temukan di belahan bumi manapun` (string)
- venueId: `1536250994397` (string, required)
- coordinate (object)
    - latitude: `-6.932567` (string, required)
    - longitude: `107.870124` (string, required)
- address (Address)
- contact (Contact)

## Feedback (object)
- id: `1536250994397` (string, required)
- venueId: `1536250994397` (string, required)
- photo (array[string]) - only 1 image
    - asd.png
- personName: `Alif Akbar` (string, required)
- comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.` (string, required)
- loveMeter: 5 (number, required)
- city: `Jakarta` (string)

## Facility (object)
- icon: `asd.png` (string)
- description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.` (string, required)
- shortDescription: `Lorem ipsum dolor sit amet` (string, required)

## Attraction (object)
- icon: `asd.png` (string)
- backgroundImage: `asd.png` (string)
- description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.` (string, required)
- shortDescription: `Camping Ground` (string, required)